project:
  type: website
  output-dir: docs

website:
  title: "kasiawojczulanis"
  navbar:
    left:
      - href: index.qmd
        text: About
      - projects.qmd
      - publications.qmd
      - teaching.qmd
      - miscellaneous.qmd

format:
  html:
    theme: 
      light: spacelab
      dark: darkly 
    css: styles.css
    toc: true

editor: visual

