project:
  type: website
  output-dir: docs

website:
  title: "kasiawojczulanis"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - publications.qmd

format:
  html:
    theme: 
      light: spacelab
      dark: darkly 
    css: styles.css
    toc: true

editor: visual

