---
title: "Miscellaneous"
format:
  html:
    css: styles.css
---

### Fieldwork on Svalbard

Since 2003, my research group (and that includes me), we are working in breeding colonies of the little auk on Svalbard. For most of the years, we work in Hornsund colony (S Spitsbergen), where we have established a long-term monitoring programme, to examine the [birds response to ongoing climate changes](projects.qmd#Polar%20seabirds%20response%20to%20environmantal%20changes). Here is also where we ask other research questions, about \[non-breeding ecology of seabirds\](projects.qmd#Non-breeding ecology of polar seabirds), as well as about seabirds (namely little auk) \[breeding (behavioural) ecology\](projects.qmd#Breeding (behavioural) ecology). All these questions are logistically demanding (e.g requiring continous energy supply for audio/video recording), and possible in polar environment only with a considerable logistic support from a local station (Polish Polar Station here is just irreplaceable).

Hornsund is a magical spot (look [here for a short footage](https://www.youtube.com/watch?v=q_TOWZk1OI4&feature=youtu.be)), it is a privilege to be able to work there.

Some years (including last season: 2023) we have been also working in Magdalenefjorden (NW Spitsbergen).

### Fieldwork in Tropics

Biodiversitatis: <https://biodiversitatis.com.pl/komitet-naukowy/>

### 
